// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIOuvWzwhlMIIAJ4dmmr5NEME3dy2BMDs',
    appId: '1:648100029327:web:2a5e332bd47709ce11e1fa',
    messagingSenderId: '648100029327',
    projectId: 'onetoonechat-c8f28',
    authDomain: 'onetoonechat-c8f28.firebaseapp.com',
    storageBucket: 'onetoonechat-c8f28.firebasestorage.app',
    measurementId: 'G-JV0VLP6JJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDHHsNF0RmFOi8DRCUc1QT8dcQlip4mo',
    appId: '1:648100029327:android:93d2c9fd70a1927a11e1fa',
    messagingSenderId: '648100029327',
    projectId: 'onetoonechat-c8f28',
    storageBucket: 'onetoonechat-c8f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyAfkcqEPvxGb_nKzNGHtk7mOltncVuKg',
    appId: '1:648100029327:ios:0d298485e6204d4711e1fa',
    messagingSenderId: '648100029327',
    projectId: 'onetoonechat-c8f28',
    storageBucket: 'onetoonechat-c8f28.firebasestorage.app',
    iosBundleId: 'com.example.oneToOneChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyAfkcqEPvxGb_nKzNGHtk7mOltncVuKg',
    appId: '1:648100029327:ios:0d298485e6204d4711e1fa',
    messagingSenderId: '648100029327',
    projectId: 'onetoonechat-c8f28',
    storageBucket: 'onetoonechat-c8f28.firebasestorage.app',
    iosBundleId: 'com.example.oneToOneChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIOuvWzwhlMIIAJ4dmmr5NEME3dy2BMDs',
    appId: '1:648100029327:web:e10f8c5a953ea70011e1fa',
    messagingSenderId: '648100029327',
    projectId: 'onetoonechat-c8f28',
    authDomain: 'onetoonechat-c8f28.firebaseapp.com',
    storageBucket: 'onetoonechat-c8f28.firebasestorage.app',
    measurementId: 'G-WWDZ4L8KKE',
  );
}
